version: '3'
services:
  user:
    image: user
    ports:
      - "3001:3001"
    command: node server.js
    environment:
      - PORT=3001
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DBNAME=user_db
      - ACCESS_TOKEN=${ACCESS_TOKEN}

  cart:
    image: cart
    ports:
      - "3003:3003"
    command: node server.js  
    environment:
      - PORT=3003
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DBNAME=cart_db

  product:
    image: product
    ports:
      - "3002:3002"
    command: node server.js
    environment:
      - PORT=3002
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_DBNAME=product_db
