version: '3'
services:
  user:
    image: user
    ports:
      - "3001:3001"
    command: node server.js
    env_file:
      - .env
    environment:
      - PORT=3001
      - MONGO_DBNAME=user_db

  cart:
    image: cart
    ports:
      - "3003:3003"
    command: node server.js  
    env_file:
      - .env
    environment:
      - PORT=3003
      - MONGO_DBNAME=cart_db

  product:
    image: product
    ports:
      - "3002:3002"
    command: node server.js
    env_file:
      - .env
    environment:
      - PORT=3002
      - MONGO_DBNAME=product_db
