apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: ecommerce-app
  labels:
    app: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: minac4/mern-pro-cart:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/cart_db
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9003
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health
            port: 9003
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecommerce-app
  labels:
    app: cart-service
spec:
  selector:
    app: cart-service
  ports:
  - port: 9003
    targetPort: 9003
    protocol: TCP
  type: ClusterIP 