apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce-app
data:
  NODE_ENV: "production"
  JWT_SECRET: "your-jwt-secret-key"
  MONGODB_URI: "mongodb://mongodb-service:27017/ecommerce"
  REDIS_URL: "redis://redis-service:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ecommerce-app
data:
  VITE_API_BASE_URL: "http://api.ecommerce.local"
  VITE_USER_SERVICE_URL: "http://user-service:3001"
  VITE_PRODUCT_SERVICE_URL: "http://product-service:3002"
  VITE_CART_SERVICE_URL: "http://cart-service:3003" 