apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ecommerce-app
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_API_BASE_URL
        - name: VITE_USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_USER_SERVICE_URL
        - name: VITE_PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_PRODUCT_SERVICE_URL
        - name: VITE_CART_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: VITE_CART_SERVICE_URL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ecommerce-app
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP 