apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mongodb.yaml
  - redis.yaml
  - user-service.yaml
  - product-service.yaml
  - cart-service.yaml
  - frontend.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: ecommerce-app
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/part-of: ecommerce-microservices

images:
  - name: user
    newTag: latest
  - name: product
    newTag: latest
  - name: cart
    newTag: latest
  - name: frontend
    newTag: latest 