apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecommerce-app
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # "your-jwt-secret-key"
  MONGODB_USERNAME: YWRtaW4=  # "admin"
  MONGODB_PASSWORD: cGFzc3dvcmQ=  # "password"
  REDIS_PASSWORD: cmVkaXNwYXNz  # "redispass"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ecommerce-app
type: Opaque
data:
  username: YWRtaW4=  # "admin"
  password: cGFzc3dvcmQ=  # "password" 